import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import {
  type AdvisoryFinding,
  cargoLockPaths,
  type DenyRunner,
  denyAdvisoryArguments,
  examineCheckout,
  governingDenyConfig,
  readCheckoutWaivers,
  readDenyAdvisories,
  rustVolumeLine,
  type WaiverCoverage,
} from "./rust-advisories";

// Outputs recorded from cargo-deny 0.19.5 (`--log-level info --format json
// check advisories`) on 2026-10-09, trimmed to the fields the reader uses.
// Fixture graph: one crate depending on smallvec =1.6.0 (RUSTSEC-2021-0003).
const VULNERABLE_LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fx"
version = "0.1.0"
dependencies = [
 "smallvec",
]

[[package]]
name = "smallvec"
version = "1.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1a55ca5f3b68e41c979bf8c46a6f1da892ca4db8f94023ce0bd32407573b1ac0"
`;
const SMALLVEC_ADVISORY = {
  aliases: ["CVE-2021-25900", "GHSA-43w2-9j62-hq99"],
  id: "RUSTSEC-2021-0003",
  package: "smallvec",
};
const LABELS = [{ span: "smallvec 1.6.0 registry+https://github.com/rust-lang/crates.io-index" }];
const LOG = (message: string, level = "INFO") =>
  JSON.stringify({ fields: { level, message }, type: "log" });
const SUMMARY = (errors: number, notes = 0) =>
  JSON.stringify({
    fields: { advisories: { errors, helps: 0, notes, warnings: 0 } },
    type: "summary",
  });
const VULNERABLE_RUN = {
  exitCode: 1,
  output: [
    LOG("gathered 2 crates in 72ms"),
    JSON.stringify({
      fields: {
        advisory: SMALLVEC_ADVISORY,
        code: "vulnerability",
        labels: LABELS,
        message: "Buffer overflow in SmallVec::insert_many",
        severity: "error",
      },
      type: "diagnostic",
    }),
    SUMMARY(1),
  ].join("\n"),
};
const IGNORED_RUN = {
  exitCode: 0,
  output: [
    JSON.stringify({
      fields: { code: "advisory-ignored", message: "advisory ignored", severity: "note" },
      type: "diagnostic",
    }),
    JSON.stringify({
      fields: {
        advisory: SMALLVEC_ADVISORY,
        code: "vulnerability",
        labels: LABELS,
        message: "Buffer overflow in SmallVec::insert_many",
        severity: "note",
      },
      type: "diagnostic",
    }),
    SUMMARY(0, 2),
  ].join("\n"),
};
const CLEAN_RUN = { exitCode: 0, output: SUMMARY(0) };
// Advisory database unreachable (empty CARGO_HOME advisory-dbs, proxy to a
// closed port): exit 1, one ERROR log, no summary.
const DATABASE_UNREACHABLE_RUN = {
  exitCode: 1,
  output: LOG(
    "failed to get 'FETCH_HEAD' metadata: failed to parse ISO-8601 timestamp 'fatal: cannot change to '/x/advisory-dbs/advisory-db-3157b0e258782691': No such file or directory'",
    "ERROR",
  ),
};
const SHADOWED_RUN = {
  exitCode: 1,
  output: LOG(
    "failed to fetch crates: error: current package believes it's in a workspace when it's not:",
    "ERROR",
  ),
};

const NO_WAIVER: WaiverCoverage = () => ({ covered: false, reason: "no waiver" });

const scratch: string[] = [];
afterEach(() => {
  for (const dir of scratch.splice(0)) rmSync(dir, { recursive: true, force: true });
});

function checkout(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), "rust-advisories-test-"));
  scratch.push(root);
  for (const [path, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), text);
  }
  return root;
}

const fixed =
  (run: { exitCode: number; output: string }): DenyRunner =>
  () =>
    run;

const FIXTURE = {
  "Cargo.toml": '[package]\nname = "fx"\nversion = "0.1.0"\n',
  "Cargo.lock": VULNERABLE_LOCK,
  "deny.toml": '[advisories]\nyanked = "deny"\n',
};
const TRACKED = Object.keys(FIXTURE);

describe("denyAdvisoryArguments", () => {
  test("runs the advisories check only, as JSON, keeping ignored advisories as notes", () => {
    const args = denyAdvisoryArguments("/r/Cargo.toml", "/r/deny.toml");
    expect(args.slice(args.indexOf("check"))).toEqual([
      "check",
      "--config",
      "/r/deny.toml",
      "--show-stats",
      "advisories",
    ]);
    expect(args).toContain("--locked");
    expect(args.join(" ")).toContain("--log-level info");
    expect(args.join(" ")).toContain("--format json");
  });
});

describe("lockfile discovery", () => {
  test("keeps every tracked Cargo.lock, nested ones included", () => {
    expect(cargoLockPaths(["a/Cargo.lock", "Cargo.lock", "Cargo.toml", "x/NotCargo.lock"])).toEqual(
      ["Cargo.lock", "a/Cargo.lock"],
    );
  });

  test("the governing deny.toml is the nearest one walking up", () => {
    const tracked = new Set(["deny.toml", "crates/sdk/deny.toml"]);
    expect(governingDenyConfig("crates/sdk/Cargo.lock", tracked)).toBe("crates/sdk/deny.toml");
    expect(governingDenyConfig("tools/oracle/Cargo.lock", tracked)).toBe("deny.toml");
    expect(governingDenyConfig("Cargo.lock", new Set<string>())).toBeNull();
  });
});

describe("readDenyAdvisories", () => {
  test("a known advisory is a finding of a run that answered", () => {
    const reading = readDenyAdvisories(VULNERABLE_RUN.exitCode, VULNERABLE_RUN.output);
    expect(reading.ran).toBe(true);
    expect(reading.reported.map((finding) => finding.id)).toEqual(["RUSTSEC-2021-0003"]);
    expect(reading.reported[0]?.crate).toBe("smallvec");
  });

  test("an unreachable advisory database is an unanswered question, never zero", () => {
    const reading = readDenyAdvisories(
      DATABASE_UNREACHABLE_RUN.exitCode,
      DATABASE_UNREACHABLE_RUN.output,
    );
    expect(reading.ran).toBe(false);
    expect(reading.detail).toContain("FETCH_HEAD");
  });

  test("a failing exit without an advisory diagnostic does not count as clean", () => {
    expect(readDenyAdvisories(1, SUMMARY(0)).ran).toBe(false);
  });

  test("an empty output, even with exit 0, is not a clean run", () => {
    expect(readDenyAdvisories(0, "").ran).toBe(false);
  });

  test("an ignored advisory is kept apart for the waiver discipline", () => {
    const reading = readDenyAdvisories(IGNORED_RUN.exitCode, IGNORED_RUN.output);
    expect(reading.ran).toBe(true);
    expect(reading.reported).toEqual([]);
    expect(reading.ignored.map((finding) => finding.id)).toEqual(["RUSTSEC-2021-0003"]);
  });
});

describe("examineCheckout", () => {
  test("reports the known advisory of the fixture lockfile and its volume", () => {
    const root = checkout(FIXTURE);
    const [result] = examineCheckout(
      root,
      ["Cargo.lock"],
      TRACKED,
      fixed(VULNERABLE_RUN),
      NO_WAIVER,
    );
    expect(result?.ok).toBe(false);
    expect(result?.answered).toBe(true);
    expect(result?.packages).toBe(2);
    expect(result?.uncovered).toEqual(["RUSTSEC-2021-0003 (smallvec)"]);
  });

  test("a clean run passes and still says how much it examined", () => {
    const root = checkout(FIXTURE);
    const [result] = examineCheckout(root, ["Cargo.lock"], TRACKED, fixed(CLEAN_RUN), NO_WAIVER);
    expect(result?.ok).toBe(true);
    expect(result?.note).toContain("2 package(s) examined");
  });

  test("a declared Cargo.lock the checkout cannot read is a failure", () => {
    const root = checkout({ ...FIXTURE, "Cargo.lock": "" });
    rmSync(join(root, "Cargo.lock"));
    mkdirSync(join(root, "Cargo.lock"));
    const [result] = examineCheckout(root, ["Cargo.lock"], TRACKED, fixed(CLEAN_RUN), NO_WAIVER);
    expect(result?.ok).toBe(false);
    expect(result?.answered).toBe(false);
    expect(result?.note).toContain("UNREADABLE");
  });

  test("a Cargo.lock without any package is not a clean graph", () => {
    const root = checkout({ ...FIXTURE, "Cargo.lock": "version = 4\n" });
    const [result] = examineCheckout(root, ["Cargo.lock"], TRACKED, fixed(CLEAN_RUN), NO_WAIVER);
    expect(result?.ok).toBe(false);
  });

  test("an unreachable advisory database fails the examination", () => {
    const root = checkout(FIXTURE);
    const [result] = examineCheckout(
      root,
      ["Cargo.lock"],
      TRACKED,
      fixed(DATABASE_UNREACHABLE_RUN),
      NO_WAIVER,
    );
    expect(result?.ok).toBe(false);
    expect(result?.answered).toBe(false);
  });

  test("a lockfile without a governing deny.toml fails", () => {
    const root = checkout(FIXTURE);
    const [result] = examineCheckout(
      root,
      ["Cargo.lock"],
      ["Cargo.toml", "Cargo.lock"],
      fixed(CLEAN_RUN),
      NO_WAIVER,
    );
    expect(result?.ok).toBe(false);
    expect(result?.note).toContain("deny.toml");
  });

  test("a lockfile cargo resolves inside an enclosing workspace is counted apart", () => {
    const root = checkout(FIXTURE);
    const [result] = examineCheckout(root, ["Cargo.lock"], TRACKED, fixed(SHADOWED_RUN), NO_WAIVER);
    expect(result?.shadowed).toBe(true);
    expect(result?.ok).toBe(true);
    expect(result?.packages).toBe(0);
  });

  test("an ignored advisory is covered only when the waiver holds", () => {
    const root = checkout(FIXTURE);
    const covering: WaiverCoverage = (_config: string, finding: AdvisoryFinding) =>
      finding.id === "RUSTSEC-2021-0003"
        ? { covered: true, waiver: "deny.toml:4" }
        : { covered: false, reason: "no" };
    const [covered] = examineCheckout(root, ["Cargo.lock"], TRACKED, fixed(IGNORED_RUN), covering);
    expect(covered?.ok).toBe(true);
    expect(covered?.covered).toEqual(["RUSTSEC-2021-0003 (smallvec) waived by deny.toml:4"]);
    const [uncovered] = examineCheckout(
      root,
      ["Cargo.lock"],
      TRACKED,
      fixed(IGNORED_RUN),
      NO_WAIVER,
    );
    expect(uncovered?.ok).toBe(false);
  });
});

describe("readCheckoutWaivers — the advisory-waivers gate's own reading", () => {
  function gitCheckout(denyToml: string): string {
    const root = checkout({ ...FIXTURE, "deny.toml": denyToml, "docs/waiver.md": "record\n" });
    const git = (args: string[]) =>
      Bun.spawnSync(["git", "-C", root, ...args], { stdout: "pipe", stderr: "pipe" });
    expect(git(["init", "--quiet"]).exitCode).toBe(0);
    expect(git(["add", "."]).exitCode).toBe(0);
    return root;
  }
  const waived = (expires: string) =>
    [
      "# waiver-review-anchor: 2026-09-01",
      "[advisories]",
      "ignore = [",
      `  "RUSTSEC-2021-0003", # smallvec insert_many unreachable here; expires=${expires}; ref=docs/waiver.md`,
      "]",
      "",
    ].join("\n");
  const finding: AdvisoryFinding = {
    id: "RUSTSEC-2021-0003",
    code: "vulnerability",
    aliases: ["GHSA-43w2-9j62-hq99"],
    crate: "smallvec",
  };

  test("a waiver valid today covers the ignored advisory", () => {
    const root = gitCheckout(waived("2026-12-31"));
    const { tracked, coverage } = readCheckoutWaivers(root, "2026-10-09");
    expect(tracked).toContain("Cargo.lock");
    expect(coverage("deny.toml", finding)).toEqual({ covered: true, waiver: "deny.toml:4" });
  });

  test("an EXPIRED waiver leaves the advisory uncovered", () => {
    const root = gitCheckout(waived("2026-10-01"));
    const { coverage } = readCheckoutWaivers(root, "2026-10-09");
    const verdict = coverage("deny.toml", finding);
    expect(verdict.covered).toBe(false);
    if (!verdict.covered) expect(verdict.reason).toContain("EXPIRED");
    const [result] = examineCheckout(root, ["Cargo.lock"], TRACKED, fixed(IGNORED_RUN), coverage);
    expect(result?.ok).toBe(false);
    expect(result?.uncovered[0]).toContain("EXPIRED");
  });

  test("an ignore with no waiver entry naming the advisory is uncovered", () => {
    const root = gitCheckout(waived("2026-12-31"));
    const { coverage } = readCheckoutWaivers(root, "2026-10-09");
    expect(
      coverage("deny.toml", { ...finding, id: "RUSTSEC-2099-0001", aliases: [], crate: "x" }),
    ).toMatchObject({ covered: false });
  });
});

describe("rustVolumeLine", () => {
  test("prints every counter, and the three outcomes sum to the declared lockfiles", () => {
    const line = rustVolumeLine({
      repositories: 10,
      declared: 13,
      examined: 12,
      shadowed: 1,
      failed: 0,
      packages: 1376,
      advisories: 0,
    });
    expect(line).toBe(
      "Rust: 10 repositories with a tracked Cargo.lock, 13 Cargo.lock declared = 12 examined + 1 shadowed + 0 failed, 1376 package(s) examined, 0 uncovered advisory(ies)",
    );
  });

  test("a sum that does not reach the declared count is said on the line", () => {
    expect(
      rustVolumeLine({
        repositories: 1,
        declared: 2,
        examined: 1,
        shadowed: 0,
        failed: 0,
        packages: 3,
        advisories: 0,
      }),
    ).toContain("COUNTING DEFECT");
  });
});
