import { buildDependencyInventory } from "./lockfile-inventory";
import type { ReportInputs } from "./report";

/**
 * Shared test fixtures. Lockfile extracts reproduce the exact on-disk shapes
 * (bun.lock JSONC with trailing commas, Cargo.lock TOML v4) so the parsers are
 * exercised against the real formats, not an idealized version of them.
 */
export const BUN_LOCK_FIXTURE = `{
  "lockfileVersion": 1,
  "configVersion": 1,
  "workspaces": {
    "": {
      "name": "@libre-ai/root",
      "devDependencies": {
        "typescript": "7.0.2",
      },
    },
    "apps/notebook": {
      "name": "@libre-ai/notebook",
      "version": "0.1.0",
      "dependencies": {
        "@libre-ai/ui": "workspace:*",
        "react": "catalog:",
      },
    },
  },
  "packages": {
    "@libre-ai/notebook": ["@libre-ai/notebook@workspace:apps/notebook"],

    "@libre-ai/ui": ["@libre-ai/ui@workspace:packages/ui"],

    "react": ["react@19.2.7", "", { "dependencies": { "scheduler": "^0.27.0" } }, "sha512-aaa"],

    "scheduler": ["scheduler@0.27.0", "", {}, "sha512-bbb"],

    "typescript": ["typescript@7.0.2", "", { "bin": { "tsc": "bin/tsc" } }, "sha512-ccc"],
  },
}
`;

export const CARGO_LOCK_FIXTURE = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "aead"
version = "0.5.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d122413f284cf2d62fb1b7db97e02edb8cda96d769b16e443a4f6195e35662b0"
dependencies = [
 "crypto-common 0.1.7",
 "generic-array",
]

[[package]]
name = "crypto-common"
version = "0.1.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa"

[[package]]
name = "generic-array"
version = "0.14.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb"

[[package]]
name = "libre-ai-core"
version = "0.1.0"
dependencies = [
 "aead",
 "somegit",
]

[[package]]
name = "somegit"
version = "1.0.0"
source = "git+https://example.org/some/repo?rev=abc123#abc123"
`;

/**
 * Nominal report inputs used by both the golden fixtures and the report
 * tests: frozen run metadata, absent attestation (the honest state until
 * positioning L3 lands), a verified restore with synthetic hashes.
 */
export function buildFixtureReportInputs(): ReportInputs {
  return {
    run: {
      date: "2026-01-02",
      commit: "0123456789abcdef0123456789abcdef01234567",
    },
    attestation: { kind: "absent" },
    restore: {
      kind: "verified",
      data: {
        sourceCommit: "1111111111111111111111111111111111111111",
        sourceTree: "2222222222222222222222222222222222222222",
        restoredCommit: "1111111111111111111111111111111111111111",
        restoredTree: "2222222222222222222222222222222222222222",
      },
    },
    inventory: buildDependencyInventory(BUN_LOCK_FIXTURE, CARGO_LOCK_FIXTURE),
  };
}
