import { describe, expect, test } from "bun:test";
import {
  buildDependencyInventory,
  parseBunLock,
  parseCargoLock,
  stripJsoncTrailingCommas,
} from "./lockfile-inventory";

// Verbatim shape of a Bun >= 1.3 text lockfile (JSONC: trailing commas), reduced
// to the structures the parser must understand: root + app workspaces, a
// workspace-resolved package, catalog-referenced and plain npm dependencies.
const BUN_LOCK_FIXTURE = `{
  "lockfileVersion": 1,
  "configVersion": 1,
  "workspaces": {
    "": {
      "name": "@libre-ai/root",
      "devDependencies": {
        "typescript": "7.0.2",
      },
    },
    "apps/notebook": {
      "name": "@libre-ai/notebook",
      "version": "0.1.0",
      "dependencies": {
        "@libre-ai/ui": "workspace:*",
        "react": "catalog:",
      },
    },
  },
  "packages": {
    "@libre-ai/notebook": ["@libre-ai/notebook@workspace:apps/notebook"],

    "@libre-ai/ui": ["@libre-ai/ui@workspace:packages/ui"],

    "react": ["react@19.2.7", "", { "dependencies": { "scheduler": "^0.27.0" } }, "sha512-aaa"],

    "scheduler": ["scheduler@0.27.0", "", {}, "sha512-bbb"],

    "typescript": ["typescript@7.0.2", "", { "bin": { "tsc": "bin/tsc" } }, "sha512-ccc"],
  },
}
`;

// Verbatim shape of a Cargo.lock version 4: crates.io packages (including
// "name version" disambiguated dependency strings), a source-less workspace
// member, and a git-sourced package to exercise non-standard classification.
const CARGO_LOCK_FIXTURE = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "aead"
version = "0.5.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d122413f284cf2d62fb1b7db97e02edb8cda96d769b16e443a4f6195e35662b0"
dependencies = [
 "crypto-common 0.1.7",
 "generic-array",
]

[[package]]
name = "crypto-common"
version = "0.1.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa"

[[package]]
name = "generic-array"
version = "0.14.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb"

[[package]]
name = "libre-ai-core"
version = "0.1.0"
dependencies = [
 "aead",
 "somegit",
]

[[package]]
name = "somegit"
version = "1.0.0"
source = "git+https://example.org/some/repo?rev=abc123#abc123"
`;

describe("stripJsoncTrailingCommas", () => {
  test("removes trailing commas before closing brackets", () => {
    const jsonc = `{"a": [1, 2,], "b": {"c": 3,},}`;
    expect(JSON.parse(stripJsoncTrailingCommas(jsonc))).toEqual({ a: [1, 2], b: { c: 3 } });
  });

  test("preserves commas and brackets inside string literals", () => {
    const jsonc = `{"s": "x,]}", "t": "esc\\",]",}`;
    expect(JSON.parse(stripJsoncTrailingCommas(jsonc))).toEqual({ s: "x,]}", t: 'esc",]' });
  });
});

describe("parseBunLock", () => {
  const inventory = parseBunLock(BUN_LOCK_FIXTURE);

  test("counts workspace packages as first-party, not external", () => {
    expect(inventory.firstParty).toBe(2);
    expect(inventory.totalExternal).toBe(3);
  });

  test("flags workspace-declared external dependencies as direct", () => {
    const byName = new Map(inventory.packages.map((p) => [p.name, p]));
    expect(byName.get("react")?.direct).toBe(true);
    expect(byName.get("typescript")?.direct).toBe(true);
    expect(byName.get("scheduler")?.direct).toBe(false);
    expect(inventory.directExternal).toBe(2);
  });

  test("splits scoped resolutions into name and version", () => {
    const ui = inventory.packages.find((p) => p.name === "@libre-ai/ui");
    expect(ui?.version).toBe("workspace:packages/ui");
    expect(ui?.registry).toBe("workspace");
  });

  test("classifies default-registry resolutions as npm", () => {
    const react = inventory.packages.find((p) => p.name === "react");
    expect(react?.registry).toBe("npm");
    expect(react?.version).toBe("19.2.7");
  });

  test("aggregates by registry deterministically", () => {
    expect(inventory.byRegistry).toEqual([
      { registry: "npm", count: 3 },
      { registry: "workspace", count: 2 },
    ]);
    expect(inventory.nonStandard).toEqual([]);
  });
});

describe("parseCargoLock", () => {
  const inventory = parseCargoLock(CARGO_LOCK_FIXTURE);

  test("classifies crates.io, path and git sources", () => {
    const byName = new Map(inventory.packages.map((p) => [p.name, p]));
    expect(byName.get("aead")?.registry).toBe("crates-io");
    expect(byName.get("libre-ai-core")?.registry).toBe("path-or-vendored");
    expect(byName.get("somegit")?.registry).toBe("git");
  });

  test("git-sourced packages surface as non-standard with their source", () => {
    expect(inventory.nonStandard).toHaveLength(1);
    expect(inventory.nonStandard.at(0)?.name).toBe("somegit");
    expect(inventory.nonStandard.at(0)?.source).toBe(
      "git+https://example.org/some/repo?rev=abc123#abc123",
    );
  });

  test("direct = dependencies of source-less (workspace/vendored) packages", () => {
    const byName = new Map(inventory.packages.map((p) => [p.name, p]));
    expect(byName.get("aead")?.direct).toBe(true);
    expect(byName.get("somegit")?.direct).toBe(true);
    expect(byName.get("crypto-common")?.direct).toBe(false);
    expect(inventory.directExternal).toBe(2);
  });

  test("parses 'name version' disambiguated dependency strings", () => {
    // crypto-common is referenced as "crypto-common 0.1.7" by aead: the parser
    // must keep only the crate name, otherwise the direct-set lookup breaks.
    const byName = new Map(inventory.packages.map((p) => [p.name, p]));
    expect(byName.has("crypto-common")).toBe(true);
  });

  test("counts totals excluding first-party packages", () => {
    expect(inventory.firstParty).toBe(1);
    expect(inventory.totalExternal).toBe(4);
    expect(inventory.byRegistry).toEqual([
      { registry: "crates-io", count: 3 },
      { registry: "git", count: 1 },
      { registry: "path-or-vendored", count: 1 },
    ]);
  });
});

describe("buildDependencyInventory", () => {
  test("combines both ecosystems and sorts package lists", () => {
    const inventory = buildDependencyInventory(BUN_LOCK_FIXTURE, CARGO_LOCK_FIXTURE);
    expect(inventory.bun.ecosystem).toBe("bun");
    expect(inventory.cargo.ecosystem).toBe("cargo");
    const bunNames = inventory.bun.packages.map((p) => p.name);
    expect(bunNames).toEqual([...bunNames].sort());
    const cargoNames = inventory.cargo.packages.map((p) => p.name);
    expect(cargoNames).toEqual([...cargoNames].sort());
  });

  test("parses the real repository lockfiles without error", async () => {
    // Guard against lockfile format drift: the real inputs of SOV-03 must
    // always parse, and this repository has no git/url dependency today.
    // Cargo.lock is optional since the governance split (ADR-0020): this
    // repository has no Rust workspace; repositories that do keep both
    // lockfiles covered.
    const repoRoot = new URL("../../", import.meta.url);
    const bunLock = await Bun.file(new URL("bun.lock", repoRoot)).text();
    const cargoLockFile = Bun.file(new URL("Cargo.lock", repoRoot));
    const cargoLock = (await cargoLockFile.exists()) ? await cargoLockFile.text() : "";
    const inventory = buildDependencyInventory(bunLock, cargoLock);
    expect(inventory.bun.totalExternal).toBeGreaterThan(0);
    if (await cargoLockFile.exists()) {
      expect(inventory.cargo.totalExternal).toBeGreaterThan(0);
    }
    const unknowns = [...inventory.bun.packages, ...inventory.cargo.packages].filter(
      (p) => p.registry === "unknown",
    );
    expect(unknowns).toEqual([]);
  });
});
