import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { collectInventory } from "./run-sovereignty";

// SOV-03 failed on every real run against this repository (2026-08-05,
// 2026-08-12): `collectInventory` read Cargo.lock unconditionally, and
// governance carries no Rust workspace (AGENTS.md, ADR-0020 split). ENOENT
// was caught and turned into `{ error }`, which report.ts's buildSov03 always
// renders as "fail" — a lockfile that legitimately does not exist read the
// same as a lockfile that failed to parse. These pin the fix: absence is not
// a parse error.

const BUN_LOCK = `{
  "lockfileVersion": 1,
  "workspaces": { "": { "name": "root" } },
  "packages": {}
}`;

let dir: string;

afterEach(async () => {
  if (dir !== undefined) await rm(dir, { recursive: true, force: true });
});

describe("collectInventory", () => {
  test("a repository with no Cargo.lock returns an inventory, not an error", async () => {
    dir = await mkdtemp(join(tmpdir(), "sovereignty-no-cargo-"));
    await writeFile(join(dir, "bun.lock"), BUN_LOCK);
    // Deliberately no Cargo.lock written — the case that broke SOV-03.

    const inventory = await collectInventory(dir);
    expect("error" in inventory).toBe(false);
    if (!("error" in inventory)) {
      expect(inventory.cargo.ecosystem).toBe("cargo");
      expect(inventory.cargo.totalExternal).toBe(0);
    }
  });

  test("a repository with both lockfiles still inventories both ecosystems", async () => {
    dir = await mkdtemp(join(tmpdir(), "sovereignty-both-"));
    await writeFile(join(dir, "bun.lock"), BUN_LOCK);
    await writeFile(
      join(dir, "Cargo.lock"),
      "# This file is automatically @generated by Cargo.\nversion = 4\n",
    );

    const inventory = await collectInventory(dir);
    expect("error" in inventory).toBe(false);
  });

  test("a genuinely missing bun.lock is still reported as an error", async () => {
    dir = await mkdtemp(join(tmpdir(), "sovereignty-no-bun-"));
    // Neither lockfile written: bun.lock's own absence must still surface —
    // only Cargo.lock's absence is legitimate.

    const inventory = await collectInventory(dir);
    expect("error" in inventory).toBe(true);
  });
});
